Document: behaviours
Title: Debian behaviours Manual
Author: <insert document author here>
Abstract: This manual describes what behaviours is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/behaviours/behaviours.sgml.gz

Format: postscript
Files: /usr/share/doc/behaviours/behaviours.ps.gz

Format: text
Files: /usr/share/doc/behaviours/behaviours.text.gz

Format: HTML
Index: /usr/share/doc/behaviours/html/index.html
Files: /usr/share/doc/behaviours/html/*.html
